# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
  app:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    links:
     - "db:db"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    restart: always
    tty: true
    stdin_open: true
